theme: jekyll-theme-cayman
repository: follow-the-sun/follow-the-sun.github.io
show_downloads: true
title: Follow the Sun
description: An study in to the state of the art "Follow the Sun" methodology of software development.
