theme: jekyll-theme-cayman
repository: follow-the-sun/follow-the-sun.github.io
show_downloads: true
title: Follow the Sun
description: An Overview of the follow the sun methodology in software development.